### ISSUE TITLE
How can I use MFA when using delegated permissions with the module?

### ISSUE THREAD

**Issue by KurtDeGreeff** [FriedrichWeinmann/EntraAuth#18]
I get below error with Connect-EntraService

WARNING: [Graph] Failed to connect: {"error":"invalid_grant","error_description":"AADSTS50076: Due to a configuration change made by your administrator, or
 because you moved to a new location, you must use multi-factor authentication to access '00000003-0000-0000-c000-000000000000'. Trace ID:
4c09211c-69e6-4820-9cf4-412d5a0de200 Correlation ID: 79725193-6c91-4518-b8df-f68a0616ab2c Timestamp: 2024-09-05
09:13:26Z","error_codes":[50076],"timestamp":"2024-09-05
09:13:26Z","trace_id":"4c09211c-69e6-4820-9cf4-412d5a0de200","correlation_id":"79725193-6c91-4518-b8df-f68a0616ab2c","error_uri":"https://login.microsofton
line.com/error?code=50076","suberror":"basic_action"}
Connect-EntraService : {"error":"invalid_grant","error_description":"AADSTS50076: Due to a configuration change made by your administrator, or because you
moved to a new location, you must use multi-factor authentication to access '00000003-0000-0000-c000-000000000000'. Trace ID:
4c09211c-69e6-4820-9cf4-412d5a0de200 Correlation ID: 79725193-6c91-4518-b8df-f68a0616ab2c Timestamp: 2024-09-05
09:13:26Z","error_codes":[50076],"timestamp":"2024-09-05 09:13:26Z","trace_id":"4c09211c-69e6-4820-9cf4-412d5a0de200","correlation_id":"79725193-6c91-4518-
b8df-f68a0616ab2c","error_uri":"https://login.microsoftonline.com/error?code=50076","suberror":"basic_action"}
At line:1 char:1
+ Connect-EntraService -Credential (Get-Secret -Name a056571AAD) -Tenan ...
+ ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
    + CategoryInfo          : InvalidOperation: (System.Net.HttpWebRequest:HttpWebRequest) [Connect-EntraService], WebException
    + FullyQualifiedErrorId : WebCmdletWebResponseException,Connect-EntraService

**Comment by FriedrichWeinmann** [comment]
Hi @KurtDeGreeff ,
sorry about the delayed response - live handed me a backlog after he vacation and ... well, response-times suffered :(
That said, to authenticate, you may have to configure the App Registration first. I've got that documented here:

https://github.com/FriedrichWeinmann/EntraAuth/blob/master/docs/overview.md

That said, that's not really the problem here:
You are using the `-Credential` parameter, which is the Resource Owner Password Credential authentication flow (RSOP), which is strongly discouraged to use and inherently incapable of MFA.
For delegate flows I recommend either Browser (preferred) or DeviceCode flows:

```powershell
# Browser / Authorization Code
Connect-EntraService -ClientID $clientID -TenantID $tenantID

# DeviceCode
Connect-EntraService -ClientID $clientID -TenantID $tenantID -DeviceCode
```
